### ISSUE TITLE
Sending events after being offline

### ISSUE THREAD

**Issue by iryna-from-meiro** [iryna-from-meiro/meiro_mobile_SDK#2]
I have tested that events are stored and sent when the app is reconnected to the network after being offline. Here are my findings:

- On iOS, events are sent only when the user launches the app after being connected to the network. This is different from Android, where events are sent immediately when the user is connected to wifi.

- On Android: events are sent immediately. However, there is a problem of duplication, where events are sent twice:
![image](https://github.com/iryna-from-meiro/meiro_mobile_SDK/assets/107461189/55f87035-be44-494f-909f-6d98acb7c421)
![image](https://github.com/iryna-from-meiro/meiro_mobile_SDK/assets/107461189/e9af65be-a161-4854-a2c6-6616ffceadde)

**Comment by olejnjak** [comment]
Moved iOS part of issue to iOS repo
