### ISSUE TITLE
New session_id is generated when user goes from 1 to 2d screen

### ISSUE THREAD

**Issue by iryna-from-meiro** [iryna-from-meiro/meiro_mobile_SDK#4]
For Android: new session_id is generated when the user goes from 1 to 2d screen.
But if I am not mistaken, it should be the same unless the user closes the app or 60 minutes have passed for the app to be in the background.

https://github.com/iryna-from-meiro/meiro_mobile_SDK/assets/107461189/9e8e2a2b-e280-4962-88c4-5a0e23a6241c

**Comment by iryna-from-meiro** [comment]
I think it doesn't happen all the time. I tried it now, and it has not changed.

**Comment by davidbilik** [comment]
> I think it doesn't happen all the time. I tried it now, and it has not changed.

haha, these issues are the best 😄 i've tried it locally and I also cannot reproduce 😞 would it be possible to try it again and find some pattern or context when this happens?

**Comment by iryna-from-meiro** [comment]
Sure, I will try to investigate this more

**Comment by iryna-from-meiro** [comment]
couldn't reproduce it any more.
