### ISSUE TITLE
Delivery of notifications when app is open

### ISSUE THREAD

**Issue by iryna-from-meiro** [iryna-from-meiro/meiro_mobile_SDK#5]
When the app is open on Android, notifications are not delivered, but they are delivered when the app is open on iOS.

**Comment by davidbilik** [comment]
Not sure how the notifications were tested, but if through the console, there is a technical limitations allowing us to only process the notifications if the app is opened. If it's closed its out of our hands. This is known "issue", once the notifications will be sent from the backend, it should work correctly

**Comment by iryna-from-meiro** [comment]
> there is a technical limitations allowing us to only process the notifications if the app is opened.

I would like to clarify that if a user has their app open on the foreground, meaning they can see it directly on their screen, and someone sends a push notification, it will not be delivered to their device. Basically, if then user puts the app on the background or closes it, this PN never comes to the device.

So is this known issue?

**Comment by adam-from-meiro** [comment]
Generally, the notifications should follow the platform default. This is a guideline for Android: https://developer.android.com/design/ui/mobile/guides/home-screen/notifications

**Comment by davidbilik** [comment]
I'm not sure who you're responding to, but the problem was in the notification payload not matching the scheme we've agreed on because it's not yet changed in your PN tool.
