### ISSUE TITLE
Delay in the `fcm_token_registered` event 

### ISSUE THREAD

**Issue by iryna-from-meiro** [iryna-from-meiro/meiro_mobile_SDK#6]
The `fcm_token_registered` event appeared only in the fifth event, and the token was `null` in the first four events (app_installed, screen view, foreground).

It's unlikely. I didn't check that when I was testing for iOS, and I don’t know if I can download the app without asking for an invitation again.

https://github.com/iryna-from-meiro/meiro_mobile_SDK/assets/107461189/f2f1386a-7e7f-4b5b-aead-853c7adcf4f3

**Comment by davidbilik** [comment]
The retrieval of the token is asynchronous, meaning that google will notify us once the token is generated and then we can act upon it. Since it happens after some time (and we can't be sure it will ever happen) it does not make sense to block sending of other events until that.
