### ISSUE TITLE
Open browser action of PN redirects user to the app

### ISSUE THREAD

**Issue by iryna-from-meiro** [iryna-from-meiro/meiro_mobile_SDK#7]
Now, regarding interactions, which I believe are on Meiro's side, I tested this: “Open browser redirects user on click to correct URL indicated in settings,” but it just opened the application—both for iOS and Android.

**Comment by olejnjak** [comment]
I think here we will need a bit more context as in my testing, app was opened but with presented in-app browser with URL that was sent in push notification.
