### ISSUE TITLE
Images are not delivered to iOS

### ISSUE THREAD

**Issue by iryna-from-meiro** [iryna-from-meiro/meiro_mobile_SDK#8]
Images are not delivered to iOS devices (but they are to Android). It shows just logo and not the actual image I used in PN.
![image](https://github.com/iryna-from-meiro/meiro_mobile_SDK/assets/107461189/ff3f1815-b41d-4d22-87bc-826ed3dde89a)

**Comment by olejnjak** [comment]
Moved iOS part of issue to iOS repo
